version: '3.8'

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: SequentialExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key_123

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.0
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Samarth \
          --lastname Gaur \
          --role Admin \
          --email admin@example.com

  webserver:
    image: apache/airflow:2.7.0
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver

  scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler

  visualize:
    build:
      context: ./visualize   # 👈 This tells Docker to build from ./visualize/Dockerfile
    container_name: weather_visualize
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    restart: unless-stopped

volumes:
  postgres_data:

